language: r
sudo: required
cache: packages

#bioc_packages:
#  - IRanges
#  - GenomicRanges

r_packages:
  - covr

r:
  - oldrel
  - release
  - devel

after_success:
  - Rscript -e 'covr::codecov()'
